---
# install_net-snmp_packages/tasks/main.yml

- name: 'Set package names on SUSE/openSUSE'
  ansible.builtin.set_fact:
    netsnmp_packages_to_be_installed: ['net-snmp', 'snmp-mibs']
  when: 'ansible_os_family == "Suse"'

- name: 'Set package names on Debian/Ubuntu'
  ansible.builtin.set_fact:
    netsnmp_packages_to_be_installed: ['libsnmp-base', 'snmp', 'snmpd', 'snmptrapd', 'libsnmp-dev']
  when: 'ansible_os_family == "Debian"'

- name: 'Set package names on CentOS/RedHat/Fedora'
  ansible.builtin.set_fact:
    netsnmp_packages_to_be_installed: ['net-snmp', 'net-snmp-utils', 'snmpcheck']
  when: 'ansible_os_family == "RedHat"'

- name: 'Install packages'
  ansible.builtin.package:
    name: "{{ netsnmp_packages_to_be_installed }}"
    state: 'present'
